const parseNumber = (value: string | undefined, fallback: number) => {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

export const env = {
  appTitle: import.meta.env.VITE_APP_TITLE || 'Camora ERP',
  appVersion: import.meta.env.VITE_APP_VERSION || '1.0.0',
  routerBasename: import.meta.env.VITE_ROUTER_BASENAME || '/',
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || '',
  apiPrefix: import.meta.env.VITE_API_PREFIX || '/api/v1',
  routeDashboard: import.meta.env.VITE_ROUTE_DASHBOARD || '/',
  routeReconcile: import.meta.env.VITE_ROUTE_RECONCILE || '/reconcile',
  routePurchaseReconcile: import.meta.env.VITE_ROUTE_RECONCILE_PURCHASES || '/reconcile-purchases',
  routeSalesAnalysis: import.meta.env.VITE_ROUTE_SALES_ANALYSIS || '/sales-analysis',
  routeSupplierMappings: import.meta.env.VITE_ROUTE_SUPPLIER_MAPPINGS || '/supplier-mappings',
  routeProductMappings: import.meta.env.VITE_ROUTE_PRODUCT_MAPPINGS || '/product-mappings',
  navDashboardLabel: import.meta.env.VITE_NAV_DASHBOARD_LABEL || 'Dashboard',
  navReconcileLabel: import.meta.env.VITE_NAV_RECONCILE_LABEL || 'Reconcile',
  navPurchaseReconcileLabel: import.meta.env.VITE_NAV_RECONCILE_PURCHASES_LABEL || 'Purchase Reconcile',
  navSalesAnalysisLabel: import.meta.env.VITE_NAV_SALES_ANALYSIS_LABEL || 'Sales Analysis',
  navSuppliersLabel: import.meta.env.VITE_NAV_SUPPLIERS_LABEL || 'Suppliers',
  navProductsLabel: import.meta.env.VITE_NAV_PRODUCTS_LABEL || 'Products',
  queryRetry: parseNumber(import.meta.env.VITE_QUERY_RETRY, 1),
  queryStaleTimeMs: parseNumber(import.meta.env.VITE_QUERY_STALE_TIME_MS, 30_000),
  resultsPollIntervalMs: parseNumber(import.meta.env.VITE_RESULTS_POLL_INTERVAL_MS, 30_000),
  matchThreshold: parseNumber(import.meta.env.VITE_MATCH_THRESHOLD, 0.01),
  defaultDateRangeMode: import.meta.env.VITE_DEFAULT_DATE_RANGE_MODE || 'current-month',
  dashboardDateLocale: import.meta.env.VITE_DASHBOARD_DATE_LOCALE || 'en-GB',
  dashboardTitle: import.meta.env.VITE_DASHBOARD_TITLE || 'Dashboard',
  dashboardLatestRunLabel: import.meta.env.VITE_DASHBOARD_LATEST_RUN_LABEL || 'Latest Run',
  dashboardBreakdownLabel: import.meta.env.VITE_DASHBOARD_BREAKDOWN_LABEL || 'Breakdown',
  dashboardRecentRunsLabel: import.meta.env.VITE_DASHBOARD_RECENT_RUNS_LABEL || 'Recent Runs',
  dashboardRecentRunsWindowLabel: import.meta.env.VITE_DASHBOARD_RECENT_RUNS_WINDOW_LABEL || 'last 12h',
  dashboardNoRunsTitle: import.meta.env.VITE_DASHBOARD_NO_RUNS_TITLE || 'No reconciliation runs yet',
  dashboardNoRunsSubtitle: import.meta.env.VITE_DASHBOARD_NO_RUNS_SUBTITLE || 'Upload your files on the Reconcile page to get started',
  dashboardGoToReconcileLabel: import.meta.env.VITE_DASHBOARD_GO_TO_RECONCILE_LABEL || 'Go to Reconcile',
  dashboardUnmappedNeedsAttentionLabel: import.meta.env.VITE_DASHBOARD_UNMAPPED_NEEDS_ATTENTION_LABEL || 'need attention',
  dashboardUnmappedClickLabel: import.meta.env.VITE_DASHBOARD_UNMAPPED_CLICK_LABEL || 'Click to review and map them',
  dashboardRunReconciliationTitle: import.meta.env.VITE_DASHBOARD_RUN_RECONCILIATION_TITLE || 'Run Reconciliation',
  dashboardRunReconciliationDesc: import.meta.env.VITE_DASHBOARD_RUN_RECONCILIATION_DESC || 'Upload rs.ge & Poster exports to compare',
  dashboardManageSuppliersTitle: import.meta.env.VITE_DASHBOARD_MANAGE_SUPPLIERS_TITLE || 'Manage Suppliers',
  dashboardMappingsConfiguredSuffix: import.meta.env.VITE_DASHBOARD_MAPPINGS_CONFIGURED_SUFFIX || 'mappings configured',
  dashboardUnmappedSuppliersTitle: import.meta.env.VITE_DASHBOARD_UNMAPPED_SUPPLIERS_TITLE || 'Unmapped Suppliers',
  dashboardAllSuppliersMappedLabel: import.meta.env.VITE_DASHBOARD_ALL_SUPPLIERS_MAPPED_LABEL || 'All suppliers mapped',
  chartMatchedColor: import.meta.env.VITE_CHART_MATCHED_COLOR || '#16a34a',
  chartDiscrepancyColor: import.meta.env.VITE_CHART_DISCREPANCY_COLOR || '#dc2626',
  chartMissingPosterColor: import.meta.env.VITE_CHART_MISSING_POSTER_COLOR || '#d97706',
  chartMissingRsgeColor: import.meta.env.VITE_CHART_MISSING_RSGE_COLOR || '#2563eb',
  reconcileTitle: import.meta.env.VITE_RECONCILE_TITLE || 'Reconciliation',
  reconcilePurchasesTitle: import.meta.env.VITE_RECONCILE_PURCHASES_TITLE || 'Purchase Reconciliation',
  salesAnalysisTitle: import.meta.env.VITE_SALES_ANALYSIS_TITLE || 'Sales Analysis',
  reconcileUploadTitle: import.meta.env.VITE_RECONCILE_UPLOAD_TITLE || 'Upload Files',
  reconcilePurchasesUploadTitle: import.meta.env.VITE_RECONCILE_PURCHASES_UPLOAD_TITLE || 'Upload Poster File',
  salesAnalysisUploadTitle: import.meta.env.VITE_SALES_ANALYSIS_UPLOAD_TITLE || 'Upload Sales & Bank Files',
  reconcileRsgeLabel: import.meta.env.VITE_RECONCILE_RSGE_LABEL || 'rs.ge Export (CSV)',
  reconcilePosterLabel: import.meta.env.VITE_RECONCILE_POSTER_LABEL || 'Poster Export (XLSX)',
  reconcilePurchasesPosterLabel: import.meta.env.VITE_RECONCILE_PURCHASES_POSTER_LABEL || 'Poster Export (XLSX)',
  salesAnalysisSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_SALES_LABEL || 'Sales',
  salesAnalysisTbcLabel: import.meta.env.VITE_SALES_ANALYSIS_TBC_LABEL || 'TBC',
  salesAnalysisBogLabel: import.meta.env.VITE_SALES_ANALYSIS_BOG_LABEL || 'BOG',
  reconcileDateFromLabel: import.meta.env.VITE_RECONCILE_DATE_FROM_LABEL || 'Date From',
  reconcileDateToLabel: import.meta.env.VITE_RECONCILE_DATE_TO_LABEL || 'Date To',
  reconcileRunLabel: import.meta.env.VITE_RECONCILE_RUN_LABEL || 'Run Analysis',
  reconcileRunningLabel: import.meta.env.VITE_RECONCILE_RUNNING_LABEL || 'Analyzing...',
  reconcilePurchasesRunLabel: import.meta.env.VITE_RECONCILE_PURCHASES_RUN_LABEL || 'Fetch Purchases & Analyze',
  reconcilePurchasesRunningLabel: import.meta.env.VITE_RECONCILE_PURCHASES_RUNNING_LABEL || 'Fetching & Analyzing...',
  salesAnalysisRunLabel: import.meta.env.VITE_SALES_ANALYSIS_RUN_LABEL || 'Analyze Sales & Banks',
  salesAnalysisRunningLabel: import.meta.env.VITE_SALES_ANALYSIS_RUNNING_LABEL || 'Analyzing Sales & Banks...',
  salesAnalysisInfo: import.meta.env.VITE_SALES_ANALYSIS_INFO || 'Upload one sales file and both bank files. Results can be viewed by day, week, or month.',
  salesAnalysisAggregationDayLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_DAY_LABEL || 'Day',
  salesAnalysisAggregationWeekLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_WEEK_LABEL || 'Week',
  salesAnalysisAggregationMonthLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_MONTH_LABEL || 'Month',
  salesAnalysisTrendChartTitle: import.meta.env.VITE_SALES_ANALYSIS_TREND_CHART_TITLE || 'Sales vs Bank Income',
  salesAnalysisBreakdownChartTitle: import.meta.env.VITE_SALES_ANALYSIS_BREAKDOWN_CHART_TITLE || 'Sales, TBC, and BOG Breakdown',
  salesAnalysisVarianceChartTitle: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_CHART_TITLE || 'Period Variance',
  salesAnalysisPeriodTableTitle: import.meta.env.VITE_SALES_ANALYSIS_PERIOD_TABLE_TITLE || 'Period Comparison',
  salesAnalysisTotalSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_TOTAL_SALES_LABEL || 'Total Sales',
  salesAnalysisTotalBankLabel: import.meta.env.VITE_SALES_ANALYSIS_TOTAL_BANK_LABEL || 'Total Bank Income',
  salesAnalysisVarianceLabel: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_LABEL || 'Variance',
  salesAnalysisCaptureRatioLabel: import.meta.env.VITE_SALES_ANALYSIS_CAPTURE_RATIO_LABEL || 'Capture Ratio',
  salesAnalysisAverageSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_AVERAGE_SALES_LABEL || 'Average Period Sales',
  salesAnalysisAverageBankLabel: import.meta.env.VITE_SALES_ANALYSIS_AVERAGE_BANK_LABEL || 'Average Period Bank Income',
  salesAnalysisStatusMatchLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_MATCH_LABEL || 'Match',
  salesAnalysisStatusShortLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_SHORT_LABEL || 'Short',
  salesAnalysisStatusOverLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_OVER_LABEL || 'Over',
  salesAnalysisStatusNoBankLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_NO_BANK_LABEL || 'No Bank Data',
  salesAnalysisStatusBankOnlyLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_BANK_ONLY_LABEL || 'Bank Only',
  salesAnalysisPeriodColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_PERIOD_COLUMN_LABEL || 'Period',
  salesAnalysisTbcColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_TBC_COLUMN_LABEL || 'TBC',
  salesAnalysisBogColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_BOG_COLUMN_LABEL || 'BOG',
  salesAnalysisCombinedBankColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_COMBINED_BANK_COLUMN_LABEL || 'Combined Bank',
  salesAnalysisSalesColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_SALES_COLUMN_LABEL || 'Sales',
  salesAnalysisVarianceColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_COLUMN_LABEL || 'Variance',
  salesAnalysisStatusColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_COLUMN_LABEL || 'Status',
  salesAnalysisRecalculateLabel: import.meta.env.VITE_SALES_ANALYSIS_RECALCULATE_LABEL || 'Recalculate & Update Accounting',
  salesAnalysisRequiresRecalcLabel: import.meta.env.VITE_SALES_ANALYSIS_REQUIRES_RECALC_LABEL || 'Files are ready. Click the button to recalculate sales accounting for the selected range.',
  salesAnalysisAlreadyCalculatedLabel: import.meta.env.VITE_SALES_ANALYSIS_ALREADY_CALCULATED_LABEL || 'These files are already analyzed for the selected range.',
  reconcilePurchasesInfo: import.meta.env.VITE_RECONCILE_PURCHASES_INFO || 'Purchase waybills are fetched live from rs.ge API. Product details may be unavailable from the API response.',
  reconcileNoResultsLabel: import.meta.env.VITE_RECONCILE_NO_RESULTS_LABEL || 'No results',
  reconcileNewSuppliersTitle: import.meta.env.VITE_RECONCILE_NEW_SUPPLIERS_TITLE || 'New unmapped suppliers discovered',
  reconcileRsgePlatformLabel: import.meta.env.VITE_RECONCILE_RSGE_PLATFORM_LABEL || 'rs.ge',
  reconcilePosterPlatformLabel: import.meta.env.VITE_RECONCILE_POSTER_PLATFORM_LABEL || 'Poster',
  reconcileCorrectionGuideLabel: import.meta.env.VITE_RECONCILE_CORRECTION_GUIDE_LABEL || 'Correction Guide',
  reconcileExportLabel: import.meta.env.VITE_RECONCILE_EXPORT_LABEL || 'Export',
  reconcileSummaryTotalLabel: import.meta.env.VITE_RECONCILE_SUMMARY_TOTAL_LABEL || 'Total Lines',
  reconcileSummaryMatchedLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MATCHED_LABEL || 'Matched',
  reconcileSummaryDiscrepancyLabel: import.meta.env.VITE_RECONCILE_SUMMARY_DISCREPANCY_LABEL || 'Discrepancy',
  reconcileSummaryMissingPosterLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MISSING_POSTER_LABEL || 'Missing in Poster',
  reconcileSummaryMissingRsgeLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MISSING_RSGE_LABEL || 'Missing in rs.ge',
  suppliersTitle: import.meta.env.VITE_SUPPLIERS_TITLE || 'Supplier Mappings',
  suppliersNewMappingLabel: import.meta.env.VITE_SUPPLIERS_NEW_MAPPING_LABEL || 'New Mapping',
  suppliersLoadingLabel: import.meta.env.VITE_SUPPLIERS_LOADING_LABEL || 'Loading...',
  suppliersMappedTitle: import.meta.env.VITE_SUPPLIERS_MAPPED_TITLE || 'Mapped Suppliers',
  suppliersNoMappingsLabel: import.meta.env.VITE_SUPPLIERS_NO_MAPPINGS_LABEL || 'No mappings yet',
  suppliersUnmappedPosterTitle: import.meta.env.VITE_SUPPLIERS_UNMAPPED_POSTER_TITLE || 'Unmapped Poster Suppliers',
  suppliersUnmappedRsgeTitle: import.meta.env.VITE_SUPPLIERS_UNMAPPED_RSGE_TITLE || 'Unmapped rs.ge Suppliers',
  suppliersUnmappedDiscoveredSuffix: import.meta.env.VITE_SUPPLIERS_UNMAPPED_DISCOVERED_SUFFIX || 'unmapped supplier%s discovered from recent uploads - review below.',
  suppliersMapLabel: import.meta.env.VITE_SUPPLIERS_MAP_LABEL || 'Map',
  suppliersExcludeLabel: import.meta.env.VITE_SUPPLIERS_EXCLUDE_LABEL || 'Exclude',
  suppliersExcludedLabel: import.meta.env.VITE_SUPPLIERS_EXCLUDED_LABEL || 'Excluded',
  suppliersNoneLabel: import.meta.env.VITE_SUPPLIERS_NONE_LABEL || 'None',
  suppliersCreateTitle: import.meta.env.VITE_SUPPLIERS_CREATE_TITLE || 'New Supplier Mapping',
  suppliersPosterAliasLabel: import.meta.env.VITE_SUPPLIERS_POSTER_ALIAS_LABEL || 'Poster Alias',
  suppliersPosterAliasPlaceholder: import.meta.env.VITE_SUPPLIERS_POSTER_ALIAS_PLACEHOLDER || 'e.g. cola',
  suppliersRsgeRawValueLabel: import.meta.env.VITE_SUPPLIERS_RSGE_RAW_VALUE_LABEL || 'rs.ge Raw Value',
  suppliersCancelLabel: import.meta.env.VITE_SUPPLIERS_CANCEL_LABEL || 'Cancel',
  suppliersSaveLabel: import.meta.env.VITE_SUPPLIERS_SAVE_LABEL || 'Save',
  suppliersDeleteTitle: import.meta.env.VITE_SUPPLIERS_DELETE_TITLE || 'Delete Mapping',
  suppliersDeleteMessage: import.meta.env.VITE_SUPPLIERS_DELETE_MESSAGE || 'This will permanently delete this supplier mapping. This cannot be undone.',
  productsTitle: import.meta.env.VITE_PRODUCTS_TITLE || 'Product Mappings',
  productsSelectSupplierLabel: import.meta.env.VITE_PRODUCTS_SELECT_SUPPLIER_LABEL || 'Select Supplier Pair',
  productsSelectSupplierPlaceholder: import.meta.env.VITE_PRODUCTS_SELECT_SUPPLIER_PLACEHOLDER || '- Select a supplier -',
  productsMappingsForPrefix: import.meta.env.VITE_PRODUCTS_MAPPINGS_FOR_PREFIX || 'Product Mappings for',
  productsAddPatternLabel: import.meta.env.VITE_PRODUCTS_ADD_PATTERN_LABEL || 'Add Pattern',
  productsNoMappingsLabel: import.meta.env.VITE_PRODUCTS_NO_MAPPINGS_LABEL || 'No product mappings for this supplier pair',
  productsPatternTestTitle: import.meta.env.VITE_PRODUCTS_PATTERN_TEST_TITLE || 'Live Pattern Test',
  productsPatternLabel: import.meta.env.VITE_PRODUCTS_PATTERN_LABEL || 'Pattern',
  productsTestValueLabel: import.meta.env.VITE_PRODUCTS_TEST_VALUE_LABEL || 'Test Value',
  productsRegexLabel: import.meta.env.VITE_PRODUCTS_REGEX_LABEL || 'Regex',
  productsTestButtonLabel: import.meta.env.VITE_PRODUCTS_TEST_BUTTON_LABEL || 'Test',
  productsPatternMatchesLabel: import.meta.env.VITE_PRODUCTS_PATTERN_MATCHES_LABEL || 'Pattern matches!',
  productsPatternNoMatchLabel: import.meta.env.VITE_PRODUCTS_PATTERN_NO_MATCH_LABEL || 'No match',
  productsAddTitle: import.meta.env.VITE_PRODUCTS_ADD_TITLE || 'Add Product Pattern',
  productsRsgePatternLabel: import.meta.env.VITE_PRODUCTS_RSGE_PATTERN_LABEL || 'rs.ge Product Pattern',
  productsPosterPatternLabel: import.meta.env.VITE_PRODUCTS_POSTER_PATTERN_LABEL || 'Poster Product Pattern',
  productsUseRegexLabel: import.meta.env.VITE_PRODUCTS_USE_REGEX_LABEL || 'Use Regex',
  productsPriorityLabel: import.meta.env.VITE_PRODUCTS_PRIORITY_LABEL || 'Priority',
  productsSavingLabel: import.meta.env.VITE_PRODUCTS_SAVING_LABEL || 'Saving...',
  productsDeleteTitle: import.meta.env.VITE_PRODUCTS_DELETE_TITLE || 'Delete Pattern',
  productsDeleteMessage: import.meta.env.VITE_PRODUCTS_DELETE_MESSAGE || 'Delete this product mapping pattern?',
  statusMatchLabel: import.meta.env.VITE_STATUS_MATCH_LABEL || 'Match',
  statusDiscrepancyLabel: import.meta.env.VITE_STATUS_DISCREPANCY_LABEL || 'Discrepancy',
  statusMissingPosterLabel: import.meta.env.VITE_STATUS_MISSING_POSTER_LABEL || 'Missing in Poster',
  statusMissingRsgeLabel: import.meta.env.VITE_STATUS_MISSING_RSGE_LABEL || 'Missing in rs.ge',
  fileDropzoneHint: import.meta.env.VITE_FILE_DROPZONE_HINT || 'Drop file here or click to browse',
  fileDropzoneRemoveLabel: import.meta.env.VITE_FILE_DROPZONE_REMOVE_LABEL || 'Remove',
  rsgeAccept: import.meta.env.VITE_RECONCILE_RSGE_ACCEPT || '.csv',
  posterAccept: import.meta.env.VITE_RECONCILE_POSTER_ACCEPT || '.xlsx,.xls',
  salesAnalysisAccept: import.meta.env.VITE_SALES_ANALYSIS_ACCEPT || '.xlsx,.xls',
  correctionGuidePrefix: import.meta.env.VITE_CORRECTION_GUIDE_PREFIX || 'correction-guide',
} as const
