const parseNumber = (value: string | undefined, fallback: number) => {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : fallback
}

export const env = {
  appTitle: import.meta.env.VITE_APP_TITLE || 'Camora ERP',
  appVersion: import.meta.env.VITE_APP_VERSION || '1.0.0',
  routerBasename: import.meta.env.VITE_ROUTER_BASENAME || '/',
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || '',
  apiPrefix: import.meta.env.VITE_API_PREFIX || '/api/v1',
  routeDashboard: import.meta.env.VITE_ROUTE_DASHBOARD || '/',
  routeReconcile: import.meta.env.VITE_ROUTE_RECONCILE || '/reconcile',
  routePurchaseReconcile: import.meta.env.VITE_ROUTE_RECONCILE_PURCHASES || '/reconcile-purchases',
  routeSalesAnalysis: import.meta.env.VITE_ROUTE_SALES_ANALYSIS || '/sales-analysis',
  routeCashFlow: import.meta.env.VITE_ROUTE_CASH_FLOW || '/cash-flow',
  routeBankAnalysis: import.meta.env.VITE_ROUTE_BANK_ANALYSIS || '/bank-analysis',
  routeSupplierDebts: import.meta.env.VITE_ROUTE_SUPPLIER_DEBTS || '/supplier-debts',
  routeSalesProducts: import.meta.env.VITE_ROUTE_SALES_PRODUCTS || '/sales-products',
  routeSupplierMappings: import.meta.env.VITE_ROUTE_SUPPLIER_MAPPINGS || '/supplier-mappings',
  routeProductMappings: import.meta.env.VITE_ROUTE_PRODUCT_MAPPINGS || '/product-mappings',
  navDashboardLabel: import.meta.env.VITE_NAV_DASHBOARD_LABEL || 'Dashboard',
  navReconcileLabel: import.meta.env.VITE_NAV_RECONCILE_LABEL || 'Reconcile',
  navPurchaseReconcileLabel: import.meta.env.VITE_NAV_RECONCILE_PURCHASES_LABEL || 'Purchase Reconcile',
  navSalesAnalysisLabel: import.meta.env.VITE_NAV_SALES_ANALYSIS_LABEL || 'Sales Analysis',
  navCashFlowLabel: import.meta.env.VITE_NAV_CASH_FLOW_LABEL || 'ფულადი ნაკადები',
  navBankAnalysisLabel: import.meta.env.VITE_NAV_BANK_ANALYSIS_LABEL || 'Bank Analysis',
  navSupplierDebtsLabel: import.meta.env.VITE_NAV_SUPPLIER_DEBTS_LABEL || 'Creditors',
  navSalesProductsLabel: import.meta.env.VITE_NAV_SALES_PRODUCTS_LABEL || 'Sales Products',
  navSuppliersLabel: import.meta.env.VITE_NAV_SUPPLIERS_LABEL || 'Suppliers',
  navProductsLabel: import.meta.env.VITE_NAV_PRODUCTS_LABEL || 'Products',
  queryRetry: parseNumber(import.meta.env.VITE_QUERY_RETRY, 1),
  queryStaleTimeMs: parseNumber(import.meta.env.VITE_QUERY_STALE_TIME_MS, 30_000),
  resultsPollIntervalMs: parseNumber(import.meta.env.VITE_RESULTS_POLL_INTERVAL_MS, 30_000),
  matchThreshold: parseNumber(import.meta.env.VITE_MATCH_THRESHOLD, 0.01),
  defaultDateRangeMode: import.meta.env.VITE_DEFAULT_DATE_RANGE_MODE || 'current-month',
  dashboardDateLocale: import.meta.env.VITE_DASHBOARD_DATE_LOCALE || 'en-GB',
  dashboardTitle: import.meta.env.VITE_DASHBOARD_TITLE || 'Dashboard',
  dashboardLatestRunLabel: import.meta.env.VITE_DASHBOARD_LATEST_RUN_LABEL || 'Latest Run',
  dashboardBreakdownLabel: import.meta.env.VITE_DASHBOARD_BREAKDOWN_LABEL || 'Breakdown',
  dashboardRecentRunsLabel: import.meta.env.VITE_DASHBOARD_RECENT_RUNS_LABEL || 'Recent Runs',
  dashboardRecentRunsWindowLabel: import.meta.env.VITE_DASHBOARD_RECENT_RUNS_WINDOW_LABEL || 'last 12h',
  dashboardNoRunsTitle: import.meta.env.VITE_DASHBOARD_NO_RUNS_TITLE || 'No reconciliation runs yet',
  dashboardNoRunsSubtitle: import.meta.env.VITE_DASHBOARD_NO_RUNS_SUBTITLE || 'Upload your files on the Reconcile page to get started',
  dashboardGoToReconcileLabel: import.meta.env.VITE_DASHBOARD_GO_TO_RECONCILE_LABEL || 'Go to Reconcile',
  dashboardUnmappedNeedsAttentionLabel: import.meta.env.VITE_DASHBOARD_UNMAPPED_NEEDS_ATTENTION_LABEL || 'need attention',
  dashboardUnmappedClickLabel: import.meta.env.VITE_DASHBOARD_UNMAPPED_CLICK_LABEL || 'Click to review and map them',
  dashboardRunReconciliationTitle: import.meta.env.VITE_DASHBOARD_RUN_RECONCILIATION_TITLE || 'Run Reconciliation',
  dashboardRunReconciliationDesc: import.meta.env.VITE_DASHBOARD_RUN_RECONCILIATION_DESC || 'Upload rs.ge & Poster exports to compare',
  dashboardManageSuppliersTitle: import.meta.env.VITE_DASHBOARD_MANAGE_SUPPLIERS_TITLE || 'Manage Suppliers',
  dashboardMappingsConfiguredSuffix: import.meta.env.VITE_DASHBOARD_MAPPINGS_CONFIGURED_SUFFIX || 'mappings configured',
  dashboardUnmappedSuppliersTitle: import.meta.env.VITE_DASHBOARD_UNMAPPED_SUPPLIERS_TITLE || 'Unmapped Suppliers',
  dashboardAllSuppliersMappedLabel: import.meta.env.VITE_DASHBOARD_ALL_SUPPLIERS_MAPPED_LABEL || 'All suppliers mapped',
  chartMatchedColor: import.meta.env.VITE_CHART_MATCHED_COLOR || '#16a34a',
  chartDiscrepancyColor: import.meta.env.VITE_CHART_DISCREPANCY_COLOR || '#dc2626',
  chartMissingPosterColor: import.meta.env.VITE_CHART_MISSING_POSTER_COLOR || '#d97706',
  chartMissingRsgeColor: import.meta.env.VITE_CHART_MISSING_RSGE_COLOR || '#2563eb',
  reconcileTitle: import.meta.env.VITE_RECONCILE_TITLE || 'Reconciliation',
  reconcilePurchasesTitle: import.meta.env.VITE_RECONCILE_PURCHASES_TITLE || 'Purchase Reconciliation',
  salesAnalysisTitle: import.meta.env.VITE_SALES_ANALYSIS_TITLE || 'Sales Analysis',
  cashFlowTitle: import.meta.env.VITE_CASH_FLOW_TITLE || 'ფულადი ნაკადები',
  bankAnalysisTitle: import.meta.env.VITE_BANK_ANALYSIS_TITLE || 'Bank Analysis',
  bankAnalysisInfo: import.meta.env.VITE_BANK_ANALYSIS_INFO || 'Fetch TBC DBI movements for a selected date range, classify credits and debits, and save reusable mapping rules.',
  bankAnalysisProviderLabel: import.meta.env.VITE_BANK_ANALYSIS_PROVIDER_LABEL || 'Provider',
  bankAnalysisTbcLabel: import.meta.env.VITE_BANK_ANALYSIS_TBC_LABEL || 'TBC',
  bankAnalysisBogLabel: import.meta.env.VITE_BANK_ANALYSIS_BOG_LABEL || 'BOG',
  bankAnalysisRunLabel: import.meta.env.VITE_BANK_ANALYSIS_RUN_LABEL || 'Fetch Movements',
  bankAnalysisRunningLabel: import.meta.env.VITE_BANK_ANALYSIS_RUNNING_LABEL || 'Fetching...',
  bankAnalysisCreditsLabel: import.meta.env.VITE_BANK_ANALYSIS_CREDITS_LABEL || 'Credits',
  bankAnalysisDebitsLabel: import.meta.env.VITE_BANK_ANALYSIS_DEBITS_LABEL || 'Debits',
  bankAnalysisNetLabel: import.meta.env.VITE_BANK_ANALYSIS_NET_LABEL || 'Net Movement',
  bankAnalysisTransactionsLabel: import.meta.env.VITE_BANK_ANALYSIS_TRANSACTIONS_LABEL || 'Transactions',
  bankAnalysisLargeCreditsLabel: import.meta.env.VITE_BANK_ANALYSIS_LARGE_CREDITS_LABEL || 'Large Unmapped Credits',
  bankAnalysisDebitReceiversLabel: import.meta.env.VITE_BANK_ANALYSIS_DEBIT_RECEIVERS_LABEL || 'Unmapped Debit Receivers',
  bankAnalysisCategoryTotalsLabel: import.meta.env.VITE_BANK_ANALYSIS_CATEGORY_TOTALS_LABEL || 'Category Totals',
  bankAnalysisMappingCategoryPlaceholder: import.meta.env.VITE_BANK_ANALYSIS_MAPPING_CATEGORY_PLACEHOLDER || 'Category name',
  bankAnalysisSaveMappingLabel: import.meta.env.VITE_BANK_ANALYSIS_SAVE_MAPPING_LABEL || 'Save Mapping',
  supplierDebtsTitle: import.meta.env.VITE_SUPPLIER_DEBTS_TITLE || 'Supplier Creditors',
  supplierDebtsInfo: import.meta.env.VITE_SUPPLIER_DEBTS_INFO || 'Fetch rs.ge purchases, subtract matched BOG/TBC debit payments and cash payments, then map unmatched transfers to suppliers.',
  reconcileUploadTitle: import.meta.env.VITE_RECONCILE_UPLOAD_TITLE || 'Upload Files',
  reconcilePurchasesUploadTitle: import.meta.env.VITE_RECONCILE_PURCHASES_UPLOAD_TITLE || 'Upload Poster File',
  salesAnalysisUploadTitle: import.meta.env.VITE_SALES_ANALYSIS_UPLOAD_TITLE || 'Upload Sales File',
  salesAnalysisBankSourceInfo: import.meta.env.VITE_SALES_ANALYSIS_BANK_SOURCE_INFO || 'საბანკო შემოსავალი (TBC/BOG) ავტომატურად მოდის ფულადი ნაკადების გვერდის კატეგორიზებული შემოსავლიდან — ბანკის ამონაწერების ატვირთვა აღარ არის საჭირო.',
  reconcileRsgeLabel: import.meta.env.VITE_RECONCILE_RSGE_LABEL || 'rs.ge Export (CSV)',
  reconcilePosterLabel: import.meta.env.VITE_RECONCILE_POSTER_LABEL || 'Poster Export (XLSX)',
  reconcilePurchasesPosterLabel: import.meta.env.VITE_RECONCILE_PURCHASES_POSTER_LABEL || 'Poster Export (XLSX)',
  salesAnalysisSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_SALES_LABEL || 'Sales',
  salesAnalysisTbcLabel: import.meta.env.VITE_SALES_ANALYSIS_TBC_LABEL || 'TBC',
  salesAnalysisBogLabel: import.meta.env.VITE_SALES_ANALYSIS_BOG_LABEL || 'BOG',
  reconcileDateFromLabel: import.meta.env.VITE_RECONCILE_DATE_FROM_LABEL || 'Date From',
  reconcileDateToLabel: import.meta.env.VITE_RECONCILE_DATE_TO_LABEL || 'Date To',
  reconcileRunLabel: import.meta.env.VITE_RECONCILE_RUN_LABEL || 'Run Analysis',
  reconcileRunningLabel: import.meta.env.VITE_RECONCILE_RUNNING_LABEL || 'Analyzing...',
  reconcilePurchasesRunLabel: import.meta.env.VITE_RECONCILE_PURCHASES_RUN_LABEL || 'Fetch Purchases & Analyze',
  reconcilePurchasesRunningLabel: import.meta.env.VITE_RECONCILE_PURCHASES_RUNNING_LABEL || 'Fetching & Analyzing...',
  salesAnalysisRunLabel: import.meta.env.VITE_SALES_ANALYSIS_RUN_LABEL || 'Analyze Sales & Banks',
  salesAnalysisRunningLabel: import.meta.env.VITE_SALES_ANALYSIS_RUNNING_LABEL || 'Analyzing Sales & Banks...',
  salesAnalysisInfo: import.meta.env.VITE_SALES_ANALYSIS_INFO || 'Upload the Poster sales file; bank income is pulled automatically from the cash-flow backend. Results can be viewed by day, week, or month.',
  cashFlowInfo: import.meta.env.VITE_CASH_FLOW_INFO || 'ფულადი ნაკადები იტვირთება BOG და TBC ბანკებიდან და კატეგორიდება წესების მიხედვით.',
  cashFlowRefreshLabel: import.meta.env.VITE_CASH_FLOW_REFRESH_LABEL || 'განახლება',
  cashFlowRefreshingLabel: import.meta.env.VITE_CASH_FLOW_REFRESHING_LABEL || 'ახლდება...',
  cashFlowDateFromLabel: import.meta.env.VITE_CASH_FLOW_DATE_FROM_LABEL || 'დან',
  cashFlowDateToLabel: import.meta.env.VITE_CASH_FLOW_DATE_TO_LABEL || 'მდე',
  cashFlowTotalLabel: import.meta.env.VITE_CASH_FLOW_TOTAL_LABEL || 'ჯამი',
  cashFlowCategoryColumnLabel: import.meta.env.VITE_CASH_FLOW_CATEGORY_COLUMN_LABEL || 'კატეგორია',
  cashFlowNoDataLabel: import.meta.env.VITE_CASH_FLOW_NO_DATA_LABEL || 'ამ პერიოდში მონაცემები არ არის.',
  cashFlowMappingSheetLabel: import.meta.env.VITE_CASH_FLOW_MAPPING_SHEET_LABEL || 'წესები',
  cashFlowMappingSheetTitle: import.meta.env.VITE_CASH_FLOW_MAPPING_SHEET_TITLE || 'კატეგორიების წესები',
  cashFlowMappingSheetInfo: import.meta.env.VITE_CASH_FLOW_MAPPING_SHEET_INFO || 'გლობალური წესები: საიდენტიფიკაციო კოდი / IBAN / დასახელება → კატეგორია.',
  cashFlowDrilldownTitle: import.meta.env.VITE_CASH_FLOW_DRILLDOWN_TITLE || 'ტრანზაქციები',
  cashFlowSelectCategoryLabel: import.meta.env.VITE_CASH_FLOW_SELECT_CATEGORY_LABEL || 'აირჩიეთ კატეგორია',
  cashFlowColDateLabel: import.meta.env.VITE_CASH_FLOW_COL_DATE_LABEL || 'თარიღი',
  cashFlowColCounterpartyLabel: import.meta.env.VITE_CASH_FLOW_COL_COUNTERPARTY_LABEL || 'კონტრაგენტი',
  cashFlowColAmountLabel: import.meta.env.VITE_CASH_FLOW_COL_AMOUNT_LABEL || 'თანხა',
  cashFlowColSourceLabel: import.meta.env.VITE_CASH_FLOW_COL_SOURCE_LABEL || 'ბანკი',
  cashFlowColCategoryLabel: import.meta.env.VITE_CASH_FLOW_COL_CATEGORY_LABEL || 'კატეგორია',
  cashFlowCascadeTitle: import.meta.env.VITE_CASH_FLOW_CASCADE_TITLE || 'კატეგორიის შეცვლა',
  cashFlowCascadeQuestion: import.meta.env.VITE_CASH_FLOW_CASCADE_QUESTION || 'როგორ გავრცელდეს ეს კატეგორია?',
  cashFlowApplyAllLabel: import.meta.env.VITE_CASH_FLOW_APPLY_ALL_LABEL || 'ყველა მსგავს ჩანაწერზე (წესის შექმნა)',
  cashFlowApplyAllInfo: import.meta.env.VITE_CASH_FLOW_APPLY_ALL_INFO || 'შეიქმნება წესი ამ კონტრაგენტისთვის და გავრცელდება ყველა მსგავს ტრანზაქციაზე.',
  cashFlowApplyOneLabel: import.meta.env.VITE_CASH_FLOW_APPLY_ONE_LABEL || 'მხოლოდ ამ ჩანაწერზე',
  cashFlowApplyOneInfo: import.meta.env.VITE_CASH_FLOW_APPLY_ONE_INFO || 'კატეგორია მიენიჭება მხოლოდ ამ ტრანზაქციას, გლობალური წესის გარეშე.',
  cashFlowRuleAddLabel: import.meta.env.VITE_CASH_FLOW_RULE_ADD_LABEL || 'წესის დამატება',
  cashFlowRuleMatchTypeLabel: import.meta.env.VITE_CASH_FLOW_RULE_MATCH_TYPE_LABEL || 'ტიპი',
  cashFlowRuleMatchValueLabel: import.meta.env.VITE_CASH_FLOW_RULE_MATCH_VALUE_LABEL || 'მნიშვნელობა',
  cashFlowRuleDeleteLabel: import.meta.env.VITE_CASH_FLOW_RULE_DELETE_LABEL || 'წაშლა',
  cashFlowStatusLabel: import.meta.env.VITE_CASH_FLOW_STATUS_LABEL || 'სტატუსი',
  cashFlowLastRefreshLabel: import.meta.env.VITE_CASH_FLOW_LAST_REFRESH_LABEL || 'ბოლო განახლება',
  cashFlowSaveLabel: import.meta.env.VITE_CASH_FLOW_SAVE_LABEL || 'შენახვა',
  cashFlowCancelLabel: import.meta.env.VITE_CASH_FLOW_CANCEL_LABEL || 'გაუქმება',
  cashFlowCategoriesLabel: import.meta.env.VITE_CASH_FLOW_CATEGORIES_LABEL || 'კატეგორიები',
  cashFlowCategoriesTitle: import.meta.env.VITE_CASH_FLOW_CATEGORIES_TITLE || 'კატეგორიების მართვა',
  cashFlowAddCategoryLabel: import.meta.env.VITE_CASH_FLOW_ADD_CATEGORY_LABEL || 'ახალი კატეგორია',
  cashFlowAddSubcategoryLabel: import.meta.env.VITE_CASH_FLOW_ADD_SUBCATEGORY_LABEL || 'ქვეკატეგორია',
  cashFlowCategoryNameLabel: import.meta.env.VITE_CASH_FLOW_CATEGORY_NAME_LABEL || 'დასახელება',
  cashFlowSectionLabel: import.meta.env.VITE_CASH_FLOW_SECTION_LABEL || 'აქტივობა',
  cashFlowDirectionLabel: import.meta.env.VITE_CASH_FLOW_DIRECTION_LABEL || 'ტიპი',
  cashFlowParentLabel: import.meta.env.VITE_CASH_FLOW_PARENT_LABEL || 'მშობელი კატეგორია',
  cashFlowInflowLabel: import.meta.env.VITE_CASH_FLOW_INFLOW_LABEL || 'შემოსავალი',
  cashFlowOutflowLabel: import.meta.env.VITE_CASH_FLOW_OUTFLOW_LABEL || 'ხარჯი',
  cashFlowAddLabel: import.meta.env.VITE_CASH_FLOW_ADD_LABEL || 'დამატება',
  cashFlowChartTitle: import.meta.env.VITE_CASH_FLOW_CHART_TITLE || 'ფულადი ნაკადების მიმოხილვა',
  cashFlowChartSalesLabel: import.meta.env.VITE_CASH_FLOW_CHART_SALES_LABEL || 'შემოსავალი (რეალიზაცია)',
  cashFlowChartNetLabel: import.meta.env.VITE_CASH_FLOW_CHART_NET_LABEL || 'წმინდა ნაკადი',
  cashFlowChartExpensesLabel: import.meta.env.VITE_CASH_FLOW_CHART_EXPENSES_LABEL || 'ხარჯები',
  cashFlowChartOtherLabel: import.meta.env.VITE_CASH_FLOW_CHART_OTHER_LABEL || 'სხვა ხარჯები',
  cashFlowTabActualsLabel: import.meta.env.VITE_CASH_FLOW_TAB_ACTUALS_LABEL || 'ფაქტობრივი',
  cashFlowTabForecastLabel: import.meta.env.VITE_CASH_FLOW_TAB_FORECAST_LABEL || 'ბიუჯეტი / პროგნოზი',
  budgetInfo: import.meta.env.VITE_BUDGET_INFO || 'პროგნოზი აგებულია წინა წლის იმავე პერიოდზე, ზრდის ტემპსა და ბოლო თვეების ტენდენციაზე დაყრდნობით. ნებისმიერი ციფრი ხელით რედაქტირებადია.',
  budgetCategoryColumnLabel: import.meta.env.VITE_BUDGET_CATEGORY_COLUMN_LABEL || 'კატეგორია',
  budgetIncomeLabel: import.meta.env.VITE_BUDGET_INCOME_LABEL || 'შემოსავლები',
  budgetExpenseLabel: import.meta.env.VITE_BUDGET_EXPENSE_LABEL || 'ხარჯები',
  budgetTotalIncomeLabel: import.meta.env.VITE_BUDGET_TOTAL_INCOME_LABEL || 'ჯამური შემოსავალი',
  budgetTotalExpenseLabel: import.meta.env.VITE_BUDGET_TOTAL_EXPENSE_LABEL || 'ჯამური ხარჯი',
  budgetNetLabel: import.meta.env.VITE_BUDGET_NET_LABEL || 'წმინდა ნაკადი',
  budgetWeekGroupLabel: import.meta.env.VITE_BUDGET_WEEK_GROUP_LABEL || 'კვირები',
  budgetMonthGroupLabel: import.meta.env.VITE_BUDGET_MONTH_GROUP_LABEL || 'თვეები',
  budgetResetLabel: import.meta.env.VITE_BUDGET_RESET_LABEL || 'ალგორითმზე დაბრუნება',
  budgetEditedLabel: import.meta.env.VITE_BUDGET_EDITED_LABEL || 'რედაქტირებული',
  budgetLoadingLabel: import.meta.env.VITE_BUDGET_LOADING_LABEL || 'იტვირთება...',
  budgetNoDataLabel: import.meta.env.VITE_BUDGET_NO_DATA_LABEL || 'პროგნოზისთვის საკმარისი ისტორია არ არის.',
  budgetChartTitle: import.meta.env.VITE_BUDGET_CHART_TITLE || 'პროგნოზი: შემოსავალი, ხარჯი და წმინდა ნაკადი',
  budgetUncategorizedHint: import.meta.env.VITE_BUDGET_UNCATEGORIZED_HINT || 'ისტორიის ნაწილი არაკლასიფიცირებულია — პროგნოზი მხოლოდ კატეგორიზებულ ჩანაწერებს ითვლის. სიზუსტისთვის დააკატეგორიეთ შემოსავალი/ხარჯი ფაქტობრივ ხედში.',
  budgetBasisSeasonalLabel: import.meta.env.VITE_BUDGET_BASIS_SEASONAL_LABEL || 'წინა წლის იმავე პერიოდი × ზრდა',
  budgetBasisTrendLabel: import.meta.env.VITE_BUDGET_BASIS_TREND_LABEL || 'ბოლო პერიოდების ტენდენცია',
  budgetBasisAverageLabel: import.meta.env.VITE_BUDGET_BASIS_AVERAGE_LABEL || 'ისტორიის საშუალო',
  budgetBasisNoneLabel: import.meta.env.VITE_BUDGET_BASIS_NONE_LABEL || 'ისტორია არ არის — შეიყვანეთ ხელით',
  salesAnalysisAggregationDayLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_DAY_LABEL || 'Day',
  salesAnalysisAggregationWeekLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_WEEK_LABEL || 'Week',
  salesAnalysisAggregationMonthLabel: import.meta.env.VITE_SALES_ANALYSIS_AGGREGATION_MONTH_LABEL || 'Month',
  salesAnalysisTrendChartTitle: import.meta.env.VITE_SALES_ANALYSIS_TREND_CHART_TITLE || 'Sales vs Bank Income',
  salesAnalysisBreakdownChartTitle: import.meta.env.VITE_SALES_ANALYSIS_BREAKDOWN_CHART_TITLE || 'Sales, TBC, and BOG Breakdown',
  salesAnalysisVarianceChartTitle: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_CHART_TITLE || 'Period Variance',
  salesAnalysisProductSectionTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_SECTION_TITLE || 'Product Sales Analysis',
  salesAnalysisProductSelectorLabel: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_SELECTOR_LABEL || 'Products',
  salesAnalysisProductSelectPlaceholder: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_SELECT_PLACEHOLDER || 'Select products',
  salesAnalysisProductSearchPlaceholder: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_SEARCH_PLACEHOLDER || 'Search products',
  salesAnalysisProductNoSelectionLabel: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_NO_SELECTION_LABEL || 'Select at least one product to display the product charts.',
  salesAnalysisProductClusterTop10Label: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_CLUSTER_TOP10_LABEL || 'Top 10%',
  salesAnalysisProductClusterNext30ALabel: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_CLUSTER_NEXT30A_LABEL || 'Next 30%',
  salesAnalysisProductClusterNext30BLabel: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_CLUSTER_NEXT30B_LABEL || 'Next 30%',
  salesAnalysisProductClusterBottom30Label: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_CLUSTER_BOTTOM30_LABEL || 'Bottom 30%',
  salesAnalysisProductGrossChartTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_GROSS_CHART_TITLE || 'Gross Revenue by Product',
  salesAnalysisProductProfitChartTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_PROFIT_CHART_TITLE || 'Profit by Product',
  salesAnalysisProductQuantityChartTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_QUANTITY_CHART_TITLE || 'Quantity by Product',
  salesAnalysisProductMarginChartTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_MARGIN_CHART_TITLE || 'Profit % by Product',
  salesAnalysisProductClusterChartTitle: import.meta.env.VITE_SALES_ANALYSIS_PRODUCT_CLUSTER_CHART_TITLE || 'Product Profit Clusters',
  salesAnalysisPeriodTableTitle: import.meta.env.VITE_SALES_ANALYSIS_PERIOD_TABLE_TITLE || 'Period Comparison',
  salesAnalysisTotalSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_TOTAL_SALES_LABEL || 'Total Sales',
  salesAnalysisTotalBankLabel: import.meta.env.VITE_SALES_ANALYSIS_TOTAL_BANK_LABEL || 'Total Bank Income',
  salesAnalysisVarianceLabel: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_LABEL || 'Variance',
  salesAnalysisCaptureRatioLabel: import.meta.env.VITE_SALES_ANALYSIS_CAPTURE_RATIO_LABEL || 'Capture Ratio',
  salesAnalysisAverageSalesLabel: import.meta.env.VITE_SALES_ANALYSIS_AVERAGE_SALES_LABEL || 'Average Period Sales',
  salesAnalysisAverageBankLabel: import.meta.env.VITE_SALES_ANALYSIS_AVERAGE_BANK_LABEL || 'Average Period Bank Income',
  salesAnalysisStatusMatchLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_MATCH_LABEL || 'Match',
  salesAnalysisStatusShortLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_SHORT_LABEL || 'Short',
  salesAnalysisStatusOverLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_OVER_LABEL || 'Over',
  salesAnalysisStatusNoBankLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_NO_BANK_LABEL || 'No Bank Data',
  salesAnalysisStatusBankOnlyLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_BANK_ONLY_LABEL || 'Bank Only',
  salesAnalysisPeriodColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_PERIOD_COLUMN_LABEL || 'Period',
  salesAnalysisTbcColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_TBC_COLUMN_LABEL || 'TBC',
  salesAnalysisBogColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_BOG_COLUMN_LABEL || 'BOG',
  salesAnalysisCombinedBankColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_COMBINED_BANK_COLUMN_LABEL || 'Combined Bank',
  salesAnalysisSalesColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_SALES_COLUMN_LABEL || 'Sales',
  salesAnalysisVarianceColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_VARIANCE_COLUMN_LABEL || 'Variance',
  salesAnalysisStatusColumnLabel: import.meta.env.VITE_SALES_ANALYSIS_STATUS_COLUMN_LABEL || 'Status',
  salesAnalysisRecalculateLabel: import.meta.env.VITE_SALES_ANALYSIS_RECALCULATE_LABEL || 'Recalculate & Update Accounting',
  salesAnalysisRequiresRecalcLabel: import.meta.env.VITE_SALES_ANALYSIS_REQUIRES_RECALC_LABEL || 'Files are ready. Click the button to recalculate sales accounting for the selected range.',
  salesAnalysisAlreadyCalculatedLabel: import.meta.env.VITE_SALES_ANALYSIS_ALREADY_CALCULATED_LABEL || 'These files are already analyzed for the selected range.',
  salesAnalysisManageProductsLabel: import.meta.env.VITE_SALES_ANALYSIS_MANAGE_PRODUCTS_LABEL || 'Manage Excluded Products',
  salesAnalysisExcludedCountLabel: import.meta.env.VITE_SALES_ANALYSIS_EXCLUDED_COUNT_LABEL || 'Excluded products',
  salesAnalysisEventManagerTitle: import.meta.env.VITE_SALES_ANALYSIS_EVENT_MANAGER_TITLE || 'Events',
  salesAnalysisEventDateLabel: import.meta.env.VITE_SALES_ANALYSIS_EVENT_DATE_LABEL || 'Event Date',
  salesAnalysisEventNameLabel: import.meta.env.VITE_SALES_ANALYSIS_EVENT_NAME_LABEL || 'Event Name',
  salesAnalysisEventSaveLabel: import.meta.env.VITE_SALES_ANALYSIS_EVENT_SAVE_LABEL || 'Save Event',
  salesAnalysisEventDeleteLabel: import.meta.env.VITE_SALES_ANALYSIS_EVENT_DELETE_LABEL || 'Delete Event',
  salesAnalysisEventFilterLabel: import.meta.env.VITE_SALES_ANALYSIS_EVENT_FILTER_LABEL || 'Filter by Events',
  salesAnalysisEventCompareTitle: import.meta.env.VITE_SALES_ANALYSIS_EVENT_COMPARE_TITLE || 'Event vs Non-Event Days',
  salesAnalysisSelectedEventsLabel: import.meta.env.VITE_SALES_ANALYSIS_SELECTED_EVENTS_LABEL || 'Selected Event Days',
  salesAnalysisNonEventsLabel: import.meta.env.VITE_SALES_ANALYSIS_NON_EVENTS_LABEL || 'Non-Event Days',
  salesProductsTitle: import.meta.env.VITE_SALES_PRODUCTS_TITLE || 'Sales Product Exclusions',
  salesProductsSearchPlaceholder: import.meta.env.VITE_SALES_PRODUCTS_SEARCH_PLACEHOLDER || 'Search products',
  salesProductsAddLabel: import.meta.env.VITE_SALES_PRODUCTS_ADD_LABEL || 'Add Product',
  salesProductsManualLabel: import.meta.env.VITE_SALES_PRODUCTS_MANUAL_LABEL || 'Manual Product Name',
  salesProductsIncludedLabel: import.meta.env.VITE_SALES_PRODUCTS_INCLUDED_LABEL || 'Included',
  salesProductsExcludedLabel: import.meta.env.VITE_SALES_PRODUCTS_EXCLUDED_LABEL || 'Excluded',
  salesProductsSourceLabel: import.meta.env.VITE_SALES_PRODUCTS_SOURCE_LABEL || 'Source',
  reconcilePurchasesInfo: import.meta.env.VITE_RECONCILE_PURCHASES_INFO || 'Purchase waybills are fetched live from rs.ge API. Product details may be unavailable from the API response.',
  reconcileNoResultsLabel: import.meta.env.VITE_RECONCILE_NO_RESULTS_LABEL || 'No results',
  reconcileNewSuppliersTitle: import.meta.env.VITE_RECONCILE_NEW_SUPPLIERS_TITLE || 'New unmapped suppliers discovered',
  reconcileRsgePlatformLabel: import.meta.env.VITE_RECONCILE_RSGE_PLATFORM_LABEL || 'rs.ge',
  reconcilePosterPlatformLabel: import.meta.env.VITE_RECONCILE_POSTER_PLATFORM_LABEL || 'Poster',
  reconcileCorrectionGuideLabel: import.meta.env.VITE_RECONCILE_CORRECTION_GUIDE_LABEL || 'Correction Guide',
  reconcileExportLabel: import.meta.env.VITE_RECONCILE_EXPORT_LABEL || 'Export',
  reconcileSummaryTotalLabel: import.meta.env.VITE_RECONCILE_SUMMARY_TOTAL_LABEL || 'Total Lines',
  reconcileSummaryMatchedLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MATCHED_LABEL || 'Matched',
  reconcileSummaryDiscrepancyLabel: import.meta.env.VITE_RECONCILE_SUMMARY_DISCREPANCY_LABEL || 'Discrepancy',
  reconcileSummaryMissingPosterLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MISSING_POSTER_LABEL || 'Missing in Poster',
  reconcileSummaryMissingRsgeLabel: import.meta.env.VITE_RECONCILE_SUMMARY_MISSING_RSGE_LABEL || 'Missing in rs.ge',
  suppliersTitle: import.meta.env.VITE_SUPPLIERS_TITLE || 'Supplier Mappings',
  suppliersNewMappingLabel: import.meta.env.VITE_SUPPLIERS_NEW_MAPPING_LABEL || 'New Mapping',
  suppliersLoadingLabel: import.meta.env.VITE_SUPPLIERS_LOADING_LABEL || 'Loading...',
  suppliersMappedTitle: import.meta.env.VITE_SUPPLIERS_MAPPED_TITLE || 'Mapped Suppliers',
  suppliersNoMappingsLabel: import.meta.env.VITE_SUPPLIERS_NO_MAPPINGS_LABEL || 'No mappings yet',
  suppliersUnmappedPosterTitle: import.meta.env.VITE_SUPPLIERS_UNMAPPED_POSTER_TITLE || 'Unmapped Poster Suppliers',
  suppliersUnmappedRsgeTitle: import.meta.env.VITE_SUPPLIERS_UNMAPPED_RSGE_TITLE || 'Unmapped rs.ge Suppliers',
  suppliersUnmappedDiscoveredSuffix: import.meta.env.VITE_SUPPLIERS_UNMAPPED_DISCOVERED_SUFFIX || 'unmapped supplier%s discovered from recent uploads - review below.',
  suppliersMapLabel: import.meta.env.VITE_SUPPLIERS_MAP_LABEL || 'Map',
  suppliersExcludeLabel: import.meta.env.VITE_SUPPLIERS_EXCLUDE_LABEL || 'Exclude',
  suppliersExcludedLabel: import.meta.env.VITE_SUPPLIERS_EXCLUDED_LABEL || 'Excluded',
  suppliersNoneLabel: import.meta.env.VITE_SUPPLIERS_NONE_LABEL || 'None',
  suppliersCreateTitle: import.meta.env.VITE_SUPPLIERS_CREATE_TITLE || 'New Supplier Mapping',
  suppliersPosterAliasLabel: import.meta.env.VITE_SUPPLIERS_POSTER_ALIAS_LABEL || 'Poster Alias',
  suppliersPosterAliasPlaceholder: import.meta.env.VITE_SUPPLIERS_POSTER_ALIAS_PLACEHOLDER || 'e.g. cola',
  suppliersRsgeRawValueLabel: import.meta.env.VITE_SUPPLIERS_RSGE_RAW_VALUE_LABEL || 'rs.ge Raw Value',
  suppliersCancelLabel: import.meta.env.VITE_SUPPLIERS_CANCEL_LABEL || 'Cancel',
  suppliersSaveLabel: import.meta.env.VITE_SUPPLIERS_SAVE_LABEL || 'Save',
  suppliersDeleteTitle: import.meta.env.VITE_SUPPLIERS_DELETE_TITLE || 'Delete Mapping',
  suppliersDeleteMessage: import.meta.env.VITE_SUPPLIERS_DELETE_MESSAGE || 'This will permanently delete this supplier mapping. This cannot be undone.',
  productsTitle: import.meta.env.VITE_PRODUCTS_TITLE || 'Product Mappings',
  productsSelectSupplierLabel: import.meta.env.VITE_PRODUCTS_SELECT_SUPPLIER_LABEL || 'Select Supplier Pair',
  productsSelectSupplierPlaceholder: import.meta.env.VITE_PRODUCTS_SELECT_SUPPLIER_PLACEHOLDER || '- Select a supplier -',
  productsMappingsForPrefix: import.meta.env.VITE_PRODUCTS_MAPPINGS_FOR_PREFIX || 'Product Mappings for',
  productsAddPatternLabel: import.meta.env.VITE_PRODUCTS_ADD_PATTERN_LABEL || 'Add Pattern',
  productsNoMappingsLabel: import.meta.env.VITE_PRODUCTS_NO_MAPPINGS_LABEL || 'No product mappings for this supplier pair',
  productsPatternTestTitle: import.meta.env.VITE_PRODUCTS_PATTERN_TEST_TITLE || 'Live Pattern Test',
  productsPatternLabel: import.meta.env.VITE_PRODUCTS_PATTERN_LABEL || 'Pattern',
  productsTestValueLabel: import.meta.env.VITE_PRODUCTS_TEST_VALUE_LABEL || 'Test Value',
  productsRegexLabel: import.meta.env.VITE_PRODUCTS_REGEX_LABEL || 'Regex',
  productsTestButtonLabel: import.meta.env.VITE_PRODUCTS_TEST_BUTTON_LABEL || 'Test',
  productsPatternMatchesLabel: import.meta.env.VITE_PRODUCTS_PATTERN_MATCHES_LABEL || 'Pattern matches!',
  productsPatternNoMatchLabel: import.meta.env.VITE_PRODUCTS_PATTERN_NO_MATCH_LABEL || 'No match',
  productsAddTitle: import.meta.env.VITE_PRODUCTS_ADD_TITLE || 'Add Product Pattern',
  productsRsgePatternLabel: import.meta.env.VITE_PRODUCTS_RSGE_PATTERN_LABEL || 'rs.ge Product Pattern',
  productsPosterPatternLabel: import.meta.env.VITE_PRODUCTS_POSTER_PATTERN_LABEL || 'Poster Product Pattern',
  productsUseRegexLabel: import.meta.env.VITE_PRODUCTS_USE_REGEX_LABEL || 'Use Regex',
  productsPriorityLabel: import.meta.env.VITE_PRODUCTS_PRIORITY_LABEL || 'Priority',
  productsSavingLabel: import.meta.env.VITE_PRODUCTS_SAVING_LABEL || 'Saving...',
  productsDeleteTitle: import.meta.env.VITE_PRODUCTS_DELETE_TITLE || 'Delete Pattern',
  productsDeleteMessage: import.meta.env.VITE_PRODUCTS_DELETE_MESSAGE || 'Delete this product mapping pattern?',
  statusMatchLabel: import.meta.env.VITE_STATUS_MATCH_LABEL || 'Match',
  statusDiscrepancyLabel: import.meta.env.VITE_STATUS_DISCREPANCY_LABEL || 'Discrepancy',
  statusMissingPosterLabel: import.meta.env.VITE_STATUS_MISSING_POSTER_LABEL || 'Missing in Poster',
  statusMissingRsgeLabel: import.meta.env.VITE_STATUS_MISSING_RSGE_LABEL || 'Missing in rs.ge',
  fileDropzoneHint: import.meta.env.VITE_FILE_DROPZONE_HINT || 'Drop file here or click to browse',
  fileDropzoneRemoveLabel: import.meta.env.VITE_FILE_DROPZONE_REMOVE_LABEL || 'Remove',
  rsgeAccept: import.meta.env.VITE_RECONCILE_RSGE_ACCEPT || '.csv',
  posterAccept: import.meta.env.VITE_RECONCILE_POSTER_ACCEPT || '.xlsx,.xls',
  salesAnalysisAccept: import.meta.env.VITE_SALES_ANALYSIS_ACCEPT || '.xlsx,.xls',
  correctionGuidePrefix: import.meta.env.VITE_CORRECTION_GUIDE_PREFIX || 'correction-guide',
} as const
